name: CI

on:
  push:
    paths:
      - "api-js/**"
      - ".github/workflows/ci*.yml"
  pull_request:
    paths:
      - "api-js/**"
      - ".github/workflows/ci*.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-build.yml

  unit_tests:
    name: Unit Tests
    uses: ./.github/workflows/ci-unit-tests.yml
    needs: build