name: CI

on:
  push:
    paths:
      - "api-js/**"
      - ".github/workflows/ci*.yml"
  pull_request:
    paths:
      - "api-js/**"
      - ".github/workflows/ci*.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/ci-build.yml

  unit_tests:
    name: Unit Tests
    uses: ./.github/workflows/ci-unit-tests.yml
    needs: build

  integration_tests:
    name: Integration Tests
    uses: ./.github/workflows/ci-integration-tests.yml
    needs: build
    with:
      db_name: db_exercicio
      db_user: postgres
      db_host: 127.0.0.1
      db_dialect: postgres
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}